"""Set default value roles column

Revision ID: c448d577308e
Revises: 
Create Date: 2024-08-02 00:49:25.233048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c448d577308e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('polls_postid_fkey', 'polls', type_='foreignkey')
    op.drop_column('polls', 'postid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('postid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('polls_postid_fkey', 'polls', 'posts', ['postid'], ['postid'])
    # ### end Alembic commands ###
